### ISSUE TITLE
Soundcard not found after MM install

### ISSUE THREAD

**Issue by bravozulu1979** [sdetweil/MagicMirror_scripts#16]
I am trying to use Google AIY with Magic Mirror. I am installing Google AIY using the AIY + Rasbian buster img from the Google website. After configuring AIY, I successfully test the voice input and output as well as the assistant modules. However, as soon as I install MM and reboot, arecord -l starts returning "arecord: device_list:272: no soundcards found..." . What am I missing here !!

**Comment by bravozulu1979** [comment]
My Mic is not USB .. its built into the voice bonnet from Google which goes into the 40 pin connector.

**Comment by nmilenko** [comment]
@bravozulu1979 I also had this problem with the AIY Voice Kit V2. I reached out to their support team about a month ago and they confirmed that the current driver code is not compatible with the latest Linux kernel. A bug was filed with their dev team - I'll let you know if I hear anything on this. Hoping it's sooner rather than ~~never~~ later.

**Comment by sdetweil** [comment]
@nmilenko  thanks for the update.. so that means when the installed for sudp apt-get upgrade, it installs the new kernel. 

I don't know if you can get around that by doing manual install 
```
git clone mm repo
cd MagicMirror
npm install
```

many times this fails because some dependencies are not met, and we need the upgrade.. but u can try.

I wonder if there is a way to detect this platform
can u run 
```
lsb_release -a
or
uname -a
```
and show the results

**Comment by nmilenko** [comment]
@sdetweil see below!

`$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ uname -a
Linux raspberrypi 5.4.51+ #1327 Thu Jul 23 10:53:06 BST 2020 armv6l GNU/Linux
`
The dev team also just got back to me that there should be a new release for the AIY Voice Kit by the end of next month which is expected to fix the issue surrounding the latest kernel.

**Comment by sdetweil** [comment]
@nmilenko did u get any info on the updated AIY kit?

**Comment by sdetweil** [comment]
closed, not MM or installer problem

**Comment by nmilenko** [comment]
> @nmilenko did u get any info on the updated AIY kit?

@sdetweil Unfortunately I have not. Seems another user is looking into the kernel though.

Link below in case anyone else runs into the issue:
https://github.com/google/aiyprojects-raspbian/issues/697#issuecomment-701305599

**Comment by viraniac** [comment]
@nmilenko I have got the voicebonnet working with the latest raspbian packages.

Please find the updated deb file and instructions [here](https://github.com/google/aiyprojects-raspbian/issues/697#issuecomment-703084054).

If you already have aiy-voicebonnet-soundcard-dkms installed, uninstall it before installing my deb file

**Comment by nmilenko** [comment]
@viraniac thanks a ton, I'll give this a shot when I have some free time this weekend. Appreciate your help!
