### ISSUE TITLE
WARN: invalid config Must be one or more of: dev, optional, peer

### ISSUE THREAD

**Issue by fribse** [sdetweil/MagicMirror_scripts#53]
I'm trying to update from 2.19 to 2.20 with the update script, and it shows these warnings:

```
bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" apply
No LSB modules are available.
doing test run = false
update log will be in /home/pi/MagicMirror/installers/upgrade.log
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v16.9.1
Installed Node version: v16.15.1
No Node.js upgrade necessary.
Check current NPM installation ...
NPM currently installed. Checking version number.
Minimum npm version: V7.11.2
Installed npm version: V8.11.0
No npm upgrade necessary.

saving custom.css
upgrading from version 2.19.0 to 2.20.0
fetching latest revisions
updating MagicMirror runtime, please wait
npm WARN invalid config omit="dev --no-audit --no-fund --no-update-notifier" set in command line options
npm WARN invalid config Must be one or more of: dev, optional, peer

```

Later it fails completely:

```
processing for module MMM-MyCommute please wait
----------------------------------
npm WARN invalid config omit="dev --no-audit --no-fund --no-update-notifier" set in command line options
npm WARN invalid config Must be one or more of: dev, optional, peer
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mmmmycommute@1.1.0
npm ERR! Found: stylelint@9.10.1
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^9.10.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^13.8.0" from grunt-stylelint@0.16.0
npm ERR! node_modules/grunt-stylelint
npm ERR!   dev grunt-stylelint@"^0.16.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-08-26T11_14_01_512Z-debug-0.log
processing complete for module MMM-MyCommute

```

**Comment by sdetweil** [comment]
can u send me the installers/upgrade.log

my userid at gmail

**Comment by sdetweil** [comment]
also try this from terminal window 
```
cd ~.MagicMirror
npm --omit=dev install 
```
if it fails, just do 
npm install 

on some version of npm they have a problem with the --omit=dev parm

**Comment by fribse** [comment]
Oddly, it looks like it's updated to 2.20??
The npm --omit=dev install worked fine.

**Comment by sdetweil** [comment]
thx 

the script had successfully updated the MagicMirror version, but installing the updated dependencies failed.

on THIS version of npm the --omit=dev has to come BEFORE  the word install..

sheesh..  will fix, thx

**Comment by requiemmg** [comment]
This one hit me too, just wanted to upgrade to the new version of MM, ran the script without "apply" first, then tried it with "apply" and it failed with this comment. After a reboot, MM fails to start. Another shot with the script gives me that the current version was already installed.
Bit npm install and npm --omit=dev install fail with 
`pi@smartmirror:~/MagicMirror $ npm --omit=dev install
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/pi/MagicMirror/node_modules/body-parser
npm ERR! dest /home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/body-parser' -> '/home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-02T15_04_39_888Z-debug.log`

The debug.log

`cat /home/pi/.npm/_logs/2022-10-02T15_05_14_075Z-debug.log
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
1 info using npm@8.1.2
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 15ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 8ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/pi/MagicMirror/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/pi/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 6ms
17 timing config:load:setEnvs Completed in 5ms
18 timing config:load Completed in 48ms
19 timing npm:load:configload Completed in 49ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 2ms
22 timing config:load:flatten Completed in 16ms
23 timing npm:load:cleanupLog Completed in 10ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 2ms
26 timing npm:load Completed in 91ms
27 timing arborist:ctor Completed in 6ms
28 timing idealTree:init Completed in 4168ms
29 timing idealTree:userRequests Completed in 1ms
30 silly idealTree buildDeps
31 timing idealTree:#root Completed in 3ms
32 timing idealTree:buildDeps Completed in 12ms
33 timing idealTree:fixDepFlags Completed in 1ms
34 timing idealTree Completed in 4289ms
35 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
36 timing reify:loadTrees Completed in 7024ms
37 timing reify:diffTrees Completed in 119ms
38 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/body-parser' ]
39 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/caniuse-lite' ]
40 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/depd' ]
41 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/diff' ]
42 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/electron' ]
43 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/engine.io' ]
44 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/engine.io-parser' ]
45 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/entities' ]
46 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/eslint' ]
47 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/eslint-plugin-jest' ]
48 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/eslint-plugin-jsdoc' ]
49 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/express' ]
50 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/fast-glob' ]
51 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/has-symbols' ]
52 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/helmet' ]
53 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/istanbul-reports' ]
54 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-circus' ]
55 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-cli' ]
56 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-each' ]
57 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-haste-map' ]
58 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-snapshot' ]
59 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-watcher' ]
60 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jest-worker' ]
61 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/js-sdsl' ]
62 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jsdoc-type-pratt-parser' ]
63 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/jsdom' ]
64 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/moment' ]
65 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/moment-timezone' ]
66 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/node-releases' ]
67 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/nwsapi' ]
68 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/object-inspect' ]
69 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/parse5' ]
70 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/playwright-core' ]
71 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/postcss-selector-parser' ]
72 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/pretty-format' ]
73 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/range_check' ]
74 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/resolve' ]
75 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/send' ]
76 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/sinon' ]
77 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/socket.io-parser' ]
78 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/stylelint' ]
79 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/tough-cookie' ]
80 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/typescript' ]
81 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/yargs' ]
82 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@ampproject/remapping' ]
83 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/core' ]
84 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/generator' ]
85 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/helpers' ]
86 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/plugin-syntax-typescript' ]
87 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/traverse' ]
88 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@babel/types' ]
89 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@csstools/selector-specificity' ]
90 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@eslint/eslintrc' ]
91 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jest/core' ]
92 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jridgewell/gen-mapping' ]
93 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jridgewell/resolve-uri' ]
94 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jridgewell/set-array' ]
95 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jridgewell/sourcemap-codec' ]
96 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@jridgewell/trace-mapping' ]
97 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@sinclair/typebox' ]
98 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@types/node' ]
99 silly reify mark retired [
99 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/scope-manager'
99 silly reify ]
100 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@typescript-eslint/types' ]
101 silly reify mark retired [
101 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/typescript-estree'
101 silly reify ]
102 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/@typescript-eslint/utils' ]
103 silly reify mark retired [
103 silly reify   '/home/pi/MagicMirror/node_modules/global-agent/node_modules/semver',
103 silly reify   '/home/pi/MagicMirror/node_modules/global-agent/node_modules/.bin/semver'
103 silly reify ]
104 silly reify mark retired [ '/home/pi/MagicMirror/node_modules/v8-to-istanbul' ]
105 silly reify moves {
105 silly reify   '/home/pi/MagicMirror/node_modules/body-parser': '/home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K',
105 silly reify   '/home/pi/MagicMirror/node_modules/caniuse-lite': '/home/pi/MagicMirror/node_modules/.caniuse-lite-6h1pL5No',
105 silly reify   '/home/pi/MagicMirror/node_modules/depd': '/home/pi/MagicMirror/node_modules/.depd-3f5TLa87',
105 silly reify   '/home/pi/MagicMirror/node_modules/diff': '/home/pi/MagicMirror/node_modules/.diff-1yQIot8e',
105 silly reify   '/home/pi/MagicMirror/node_modules/electron': '/home/pi/MagicMirror/node_modules/.electron-z3ldyhRv',
105 silly reify   '/home/pi/MagicMirror/node_modules/engine.io': '/home/pi/MagicMirror/node_modules/.engine.io-9aLUekpM',
105 silly reify   '/home/pi/MagicMirror/node_modules/engine.io-parser': '/home/pi/MagicMirror/node_modules/.engine.io-parser-tNqKGWDW',
105 silly reify   '/home/pi/MagicMirror/node_modules/entities': '/home/pi/MagicMirror/node_modules/.entities-WSomGT6Y',
105 silly reify   '/home/pi/MagicMirror/node_modules/eslint': '/home/pi/MagicMirror/node_modules/.eslint-c5CUm12V',
105 silly reify   '/home/pi/MagicMirror/node_modules/eslint-plugin-jest': '/home/pi/MagicMirror/node_modules/.eslint-plugin-jest-uPWCfeI4',
105 silly reify   '/home/pi/MagicMirror/node_modules/eslint-plugin-jsdoc': '/home/pi/MagicMirror/node_modules/.eslint-plugin-jsdoc-kvyepASG',
105 silly reify   '/home/pi/MagicMirror/node_modules/express': '/home/pi/MagicMirror/node_modules/.express-DjTnWUb4',
105 silly reify   '/home/pi/MagicMirror/node_modules/fast-glob': '/home/pi/MagicMirror/node_modules/.fast-glob-05iAjeM0',
105 silly reify   '/home/pi/MagicMirror/node_modules/has-symbols': '/home/pi/MagicMirror/node_modules/.has-symbols-tlkeuGd5',
105 silly reify   '/home/pi/MagicMirror/node_modules/helmet': '/home/pi/MagicMirror/node_modules/.helmet-NqOILOxR',
105 silly reify   '/home/pi/MagicMirror/node_modules/istanbul-reports': '/home/pi/MagicMirror/node_modules/.istanbul-reports-FKdzXICn',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-circus': '/home/pi/MagicMirror/node_modules/.jest-circus-Y67LNApp',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-cli': '/home/pi/MagicMirror/node_modules/.jest-cli-3lANYzeg',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-each': '/home/pi/MagicMirror/node_modules/.jest-each-oy7YW1nR',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-haste-map': '/home/pi/MagicMirror/node_modules/.jest-haste-map-QOHUSduR',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-snapshot': '/home/pi/MagicMirror/node_modules/.jest-snapshot-W6yc0N2j',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-watcher': '/home/pi/MagicMirror/node_modules/.jest-watcher-oomPhnYj',
105 silly reify   '/home/pi/MagicMirror/node_modules/jest-worker': '/home/pi/MagicMirror/node_modules/.jest-worker-QYAGa2P6',
105 silly reify   '/home/pi/MagicMirror/node_modules/js-sdsl': '/home/pi/MagicMirror/node_modules/.js-sdsl-oKWrafxN',
105 silly reify   '/home/pi/MagicMirror/node_modules/jsdoc-type-pratt-parser': '/home/pi/MagicMirror/node_modules/.jsdoc-type-pratt-parser-v9lQJLmD',
105 silly reify   '/home/pi/MagicMirror/node_modules/jsdom': '/home/pi/MagicMirror/node_modules/.jsdom-iixQvz3p',
105 silly reify   '/home/pi/MagicMirror/node_modules/moment': '/home/pi/MagicMirror/node_modules/.moment-9Hgl7erk',
105 silly reify   '/home/pi/MagicMirror/node_modules/moment-timezone': '/home/pi/MagicMirror/node_modules/.moment-timezone-yHBKvdFE',
105 silly reify   '/home/pi/MagicMirror/node_modules/node-releases': '/home/pi/MagicMirror/node_modules/.node-releases-33dbyYrG',
105 silly reify   '/home/pi/MagicMirror/node_modules/nwsapi': '/home/pi/MagicMirror/node_modules/.nwsapi-0qLLYkB4',
105 silly reify   '/home/pi/MagicMirror/node_modules/object-inspect': '/home/pi/MagicMirror/node_modules/.object-inspect-uWtm6cdK',
105 silly reify   '/home/pi/MagicMirror/node_modules/parse5': '/home/pi/MagicMirror/node_modules/.parse5-z6fiUqYY',
105 silly reify   '/home/pi/MagicMirror/node_modules/playwright-core': '/home/pi/MagicMirror/node_modules/.playwright-core-vy8UGbYV',
105 silly reify   '/home/pi/MagicMirror/node_modules/postcss-selector-parser': '/home/pi/MagicMirror/node_modules/.postcss-selector-parser-iWLDDxsB',
105 silly reify   '/home/pi/MagicMirror/node_modules/pretty-format': '/home/pi/MagicMirror/node_modules/.pretty-format-Wp8aNarG',
105 silly reify   '/home/pi/MagicMirror/node_modules/range_check': '/home/pi/MagicMirror/node_modules/.range_check-IrjIs9vK',
105 silly reify   '/home/pi/MagicMirror/node_modules/resolve': '/home/pi/MagicMirror/node_modules/.resolve-arCuh5Wm',
105 silly reify   '/home/pi/MagicMirror/node_modules/send': '/home/pi/MagicMirror/node_modules/.send-DEdWmK4j',
105 silly reify   '/home/pi/MagicMirror/node_modules/sinon': '/home/pi/MagicMirror/node_modules/.sinon-snhWEqOk',
105 silly reify   '/home/pi/MagicMirror/node_modules/socket.io-parser': '/home/pi/MagicMirror/node_modules/.socket.io-parser-EDLRrMFe',
105 silly reify   '/home/pi/MagicMirror/node_modules/stylelint': '/home/pi/MagicMirror/node_modules/.stylelint-jxEbZA7o',
105 silly reify   '/home/pi/MagicMirror/node_modules/tough-cookie': '/home/pi/MagicMirror/node_modules/.tough-cookie-P2WVr3ez',
105 silly reify   '/home/pi/MagicMirror/node_modules/typescript': '/home/pi/MagicMirror/node_modules/.typescript-IsXPDfNx',
105 silly reify   '/home/pi/MagicMirror/node_modules/yargs': '/home/pi/MagicMirror/node_modules/.yargs-r1nSs2L9',
105 silly reify   '/home/pi/MagicMirror/node_modules/@ampproject/remapping': '/home/pi/MagicMirror/node_modules/@ampproject/.remapping-Z8QD9Yg0',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/core': '/home/pi/MagicMirror/node_modules/@babel/.core-qAQy2wOX',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/generator': '/home/pi/MagicMirror/node_modules/@babel/.generator-R5bn7h7s',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/helpers': '/home/pi/MagicMirror/node_modules/@babel/.helpers-z31lcjyU',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/plugin-syntax-typescript': '/home/pi/MagicMirror/node_modules/@babel/.plugin-syntax-typescript-l1PdRZKZ',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/traverse': '/home/pi/MagicMirror/node_modules/@babel/.traverse-8IcQ7eg2',
105 silly reify   '/home/pi/MagicMirror/node_modules/@babel/types': '/home/pi/MagicMirror/node_modules/@babel/.types-RrXzRx0c',
105 silly reify   '/home/pi/MagicMirror/node_modules/@csstools/selector-specificity': '/home/pi/MagicMirror/node_modules/@csstools/.selector-specificity-AH6CL2jR',
105 silly reify   '/home/pi/MagicMirror/node_modules/@eslint/eslintrc': '/home/pi/MagicMirror/node_modules/@eslint/.eslintrc-g59cnDDp',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jest/core': '/home/pi/MagicMirror/node_modules/@jest/.core-vE72SmWz',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jridgewell/gen-mapping': '/home/pi/MagicMirror/node_modules/@jridgewell/.gen-mapping-TgbjFaYp',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jridgewell/resolve-uri': '/home/pi/MagicMirror/node_modules/@jridgewell/.resolve-uri-lskAbLDL',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jridgewell/set-array': '/home/pi/MagicMirror/node_modules/@jridgewell/.set-array-zruATBoo',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jridgewell/sourcemap-codec': '/home/pi/MagicMirror/node_modules/@jridgewell/.sourcemap-codec-CnAVM7FS',
105 silly reify   '/home/pi/MagicMirror/node_modules/@jridgewell/trace-mapping': '/home/pi/MagicMirror/node_modules/@jridgewell/.trace-mapping-A9Mb9eZr',
105 silly reify   '/home/pi/MagicMirror/node_modules/@sinclair/typebox': '/home/pi/MagicMirror/node_modules/@sinclair/.typebox-VZEBiW3l',
105 silly reify   '/home/pi/MagicMirror/node_modules/@types/node': '/home/pi/MagicMirror/node_modules/@types/.node-eRopzc5i',
105 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/scope-manager': '/home/pi/MagicMirror/node_modules/@typescript-eslint/.scope-manager-PF2V2eYb',
105 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/types': '/home/pi/MagicMirror/node_modules/@typescript-eslint/.types-aoiseCMN',
105 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/typescript-estree': '/home/pi/MagicMirror/node_modules/@typescript-eslint/.typescript-estree-Wj44cc3R',
105 silly reify   '/home/pi/MagicMirror/node_modules/@typescript-eslint/utils': '/home/pi/MagicMirror/node_modules/@typescript-eslint/.utils-guJw310x',
105 silly reify   '/home/pi/MagicMirror/node_modules/global-agent/node_modules/semver': '/home/pi/MagicMirror/node_modules/global-agent/node_modules/.semver-zOmHuSQp',
105 silly reify   '/home/pi/MagicMirror/node_modules/global-agent/node_modules/.bin/semver': '/home/pi/MagicMirror/node_modules/global-agent/node_modules/.bin/.semver-kV1rHRPZ',
105 silly reify   '/home/pi/MagicMirror/node_modules/v8-to-istanbul': '/home/pi/MagicMirror/node_modules/.v8-to-istanbul-4wOA1P2p'
105 silly reify }
106 timing reify:rollback:retireShallow Completed in 67ms
107 timing command:install Completed in 7503ms
108 verbose stack Error: ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/body-parser' -> '/home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K'
109 verbose cwd /home/pi/MagicMirror
110 verbose Linux 5.15.32-v7+
111 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
112 verbose node v16.13.1
113 verbose npm  v8.1.2
114 error code ENOTEMPTY
115 error syscall rename
116 error path /home/pi/MagicMirror/node_modules/body-parser
117 error dest /home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K
118 error errno -39
119 error ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/body-parser' -> '/home/pi/MagicMirror/node_modules/.body-parser-zih7BI9K'
120 verbose exit -39`

**Comment by sdetweil** [comment]
do this.. don't know why that error, never seen it before but
do this 
```
cd ~/MagicMirror
sudo rm -rf node_modules
```
then rerun the upgrade script with force 
as the parm instead of apply

**Comment by evroom** [comment]
Can it be that the fix as suggested on August 26th did not make it to the master yet ?
Last commit for upgrade-script.sh was on August 12th.
But you will know best :-)

Had the same issue while upgrading.

Did the suggested:
```
pi@MagicPi3:~ $ cd ~/MagicMirror
pi@MagicPi3:~ $ npm --omit=dev install
```
which showed "3 moderate severity vulnerabilities".
The output suggested to run:
`npm audit fix --force`
but that "Will install electron@6.1.12, which is a breaking change", so I did not execute the command.

```
$ npm -version
8.11.0
```

**Comment by sdetweil** [comment]
NEVER run AUDIT fix

causes more problems than it fixes

it is complaining that a folder it wants to create already exists.. and?? it always overwrites by default..

**Comment by evroom** [comment]
Just to make it clear:
I had the same issue as @fribse, not as @requiemmg.
Did not run 'npm audit fix' nor 'npm audit fix --force'.
Only ran 'npm --omit=dev install' in the MagicMirror directory.
MagicMirror v2.21.0 runs without any issues on my system (up to now).

**Comment by sdetweil** [comment]
thanks, don't know where that fix went. uploaded it now

**Comment by requiemmg** [comment]
Thanks, sript ran through, now I have a black screen, think there is a dependency issue but I cant find how to resolve it...

`pi@smartmirror:~/MagicMirror $ sudo rm -rf node_modules
pi@smartmirror:~/MagicMirror $ bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" force
No LSB modules are available.
doing test run = false
update log will be in /home/pi/MagicMirror/installers/upgrade.log
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v16.9.1
Installed Node version: v16.13.1
No Node.js upgrade necessary.
Check current NPM installation ...
NPM currently installed. Checking version number.
Minimum npm version: V7.11.2
Installed npm version: V8.1.2
No npm upgrade necessary.

saving custom.css
upgrading from version 2.21.0 to 2.21.0
fetching latest revisions
updating MagicMirror runtime, please wait

> magicmirror@2.21.0 postinstall
> npm run install-vendor && npm run install-fonts && echo "MagicMirror² installation finished successfully!
> "


> magicmirror@2.21.0 install-vendor
> echo "Installing vendor files ...
> " && cd vendor && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing vendor files ...


changed 3 packages in 20s

> magicmirror@2.21.0 install-fonts
> echo "Installing fonts ...
> " && cd fonts && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing fonts ...


changed 2 packages in 5s
MagicMirror² installation finished successfully!


> magicmirror@2.21.0 prepare
> [ -f node_modules/.bin/husky ] && husky install || echo no husky installed.

no husky installed.

added 300 packages, and audited 301 packages in 1m

41 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Checking for modules with removed libraries
processing dependency changes for active modules with package.json files

processing for module MMM-Remote-Control please wait
----------------------------------
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 39 packages, and audited 40 packages in 10s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-Remote-Control

processing for module MMM-ModuleScheduler please wait
----------------------------------

added 194 packages, and audited 195 packages in 25s

28 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
processing complete for module MMM-ModuleScheduler

processing for module MMM-Spotify please wait
----------------------------------

added 4 packages, and audited 5 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-Spotify

processing for module MMM-Jast please wait
----------------------------------

added 291 packages, and audited 292 packages in 1m

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-Jast

processing for module MMM-DWD-WarnWeather please wait
----------------------------------
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 47 packages, and audited 48 packages in 6s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-DWD-WarnWeather

processing for module MMM-NINA please wait
----------------------------------

added 286 packages, and audited 287 packages in 43s

75 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-NINA

processing for module MMM-MyCommute please wait
----------------------------------
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mmmmycommute@1.1.0
npm ERR! Found: stylelint@14.13.0
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^14.6.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^13.8.0" from grunt-stylelint@0.16.0
npm ERR! node_modules/grunt-stylelint
npm ERR!   dev grunt-stylelint@"^0.16.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-03T07_33_56_187Z-debug.log
processing complete for module MMM-MyCommute

processing for module MMM-FRITZ-Box-Callmonitor please wait
----------------------------------

added 11 packages, and audited 12 packages in 6s

found 0 vulnerabilities
processing complete for module MMM-FRITZ-Box-Callmonitor

processing for module MMM-Fuel please wait
----------------------------------
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

added 537 packages, and audited 538 packages in 54s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-Fuel

processing for module MMM-Vrr please wait
----------------------------------
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.

added 338 packages, and audited 339 packages in 30s

46 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
processing complete for module MMM-Vrr

processing for module MMM-bringList please wait
----------------------------------
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 48 packages, and audited 49 packages in 5s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
processing complete for module MMM-bringList

restoring custom.css`

**Comment by sdetweil** [comment]
interesting

go to MMM-MyCommute modulr folder

do
```
rm -rf node_modules
rm package-lock.json
npm install
```

**Comment by sdetweil** [comment]
thanks all.. updated scripts now to use --omit-dev outside a variable, an npm is happy
added suppression parms for the npm install for modules to reduce the noise
